Test review E-I, #259
apache/lucenenet pull request #1014
Opened 2024-11-10 05:13 UTC by paulirwin

- [X] You've read the [Contributor Guide](https://github.com/apache/lucenenet/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://www.apache.org/foundation/policies/conduct.html).
- [X] You've included unit or integration tests for your change, where applicable.
- [X] You've included inline docs for your change, where applicable.
- [X] There's an open issue for the PR that you are making. If you'd like to propose a change, please [open an issue](https://github.com/apache/lucenenet/issues/new/choose) to discuss the change or find an existing issue.

Test review for core E-I tests

Partial #259 

## Description

This updates the tests in the E-I test assembly to match upstream Lucene for style, formatting, etc. Additionally, some minor bugs (including documentation bugs) have been fixed.

2024-11-10 16:00 UTC, paulirwin commented
@NightOwl888 Updated title to indicate the breaking changes of changing some static readonly fields to be const. This will affect any NuGet packages or custom binaries that use these fields, although it's generally not breaking from a source standpoint. We should probably do a sweep before beta 18 for other `const`-able fields.

2024-11-10 16:07 UTC, NightOwl888 commented
> @NightOwl888 Updated title to indicate the breaking changes of changing some static readonly fields to be const. This will affect any NuGet packages or custom binaries that use these fields, although it's generally not breaking from a source standpoint. We should probably do a sweep before beta 18 for other `const`-able fields.

Looks like this only affects test classes except for the `Assert` class that is part of the test framework, but there are no breaking API or behavioral changes in it. Or am I missing something?

2024-11-10 16:08 UTC, paulirwin commented
IndexWriter and ByteBlockPool have some public const changes. I can revert those if we'd rather do them as part of a separate sweep.

2024-11-10 16:11 UTC, NightOwl888 commented
> IndexWriter and ByteBlockPool have some public const changes. I can revert those if we'd rather do them as part of a separate sweep.

I see 'em. I have 7 files left to review and those 2 are at the bottom.

2024-11-10 16:18 UTC, NightOwl888 commented
If these are made const, that means they will be compiled as metadata in the consuming assembly. So any changes to the values will not be seen unless the consuming app is recompiled. 

This may or may not be a problem, though. Technically, we should never update the values on these unless porting a new version of Lucene. It would be helpful to know if Lucene ever changes values during minor or patch version bumps, though, because we will eventually catch up with them. The safest bet without knowing that is to leave them `static`. That said, I have been guilty of changing many of these to `const` recently.

2024-11-10 17:05 UTC, NightOwl888 requested changes
Nice work!

I found a few minor things to address. Please see my comments inline.

2024-11-11 15:51 UTC, paulirwin commented on src/Lucene.Net.Tests/Index/TestAddIndexes.cs
> +            internal void LaunchThreads(int numIter)
This is in a private class, but will do.

2024-11-11 16:00 UTC, paulirwin commented on src/Lucene.Net.Tests/Index/TestBinaryDocValuesUpdates.cs
> +            try {
That was unintentional, will fix.

2024-11-11 16:08 UTC, paulirwin commented on src/Lucene.Net.Tests/Index/TestDirectoryReaderReopen.cs
> +                        ReaderCouple c = outerInstance.RefreshReader(r, test, index, true);
Agreed, I'm all in favor of making methods static where possible. Slightly better performance of not having to load the `this` argument (as well as all the other `outerInstance` use). I went ahead and did that for two other methods in this class as well.

2024-11-11 16:24 UTC, paulirwin commented
@NightOwl888 All feedback items should be addressed now. Thanks!

2024-11-11 18:08 UTC, NightOwl888 commented on src/Lucene.Net.Tests/Index/TestBinaryDocValuesUpdates.cs
>              } catch (Exception e) when (e.IsUnsupportedOperationException()) {
I am guessing you intended to fix this line `} catch (Exception e) when (e.IsUnsupportedOperationException()) {` and `} finally {` also?

2024-11-12 03:55 UTC, NightOwl888 approved these changes

2024-11-12 03:55 UTC, merged