Implement ISpanAppendable in CharBlockArray and ICharTermAttribute/CharTermAttributeImpl
apache/lucenenet pull request #1028
Opened 2024-11-17 00:44 UTC by paulirwin

- [X] You've read the [Contributor Guide](https://github.com/apache/lucenenet/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://www.apache.org/foundation/policies/conduct.html).
- [X] You've included unit or integration tests for your change, where applicable.
- [ ] You've included inline docs for your change, where applicable.
- [X] There's an open issue for the PR that you are making. If you'd like to propose a change, please [open an issue](https://github.com/apache/lucenenet/issues/new/choose) to discuss the change or find an existing issue.

Implement `ISpanAppendable` in `CharBlockArray`, `ICharTermAttribute`, and `CharTermAttributeImpl`

Fixes #1026

## Description

This adds `ISpanAppendable` to the `ICharTermAttribute` interface, and `CharBlockArray` and `CharTermAttributeImpl` classes. The classes implement the interface explicitly so that we can provide a default implementation that returns itself rather than `ISpanAppendable`, to match the existing Append overloads.

The existing Append overloads that have Span-supporting types like `string` or `char[]` have been updated to call this Append method via `.AsSpan()` as what should be a more efficient implementation.

Note that while `IAppendable` is now redundant in the interface list for these types, I left it there for Lucene source compatibility and reference, since `ISpanAppendable` does not exist in Lucene.

2024-11-17 00:52 UTC, paulirwin commented
@NightOwl888 I intend to mark this ready for review once #1018 is merged, leaving as draft for now. I'll also likely have to resolve a merge conflict at that point too.

2024-11-19 11:49 UTC, NightOwl888 requested changes
Thanks for the PR.

There were a few more changes included than required. Copying spans is much less optimized on .NET Framework than using other copy methods, so we should add the `Append(ReadOnlySpan<char>)` method without changing the implementations of the other overloads. Please see the inline comments.

2024-11-19 20:38 UTC, paulirwin commented on src/Lucene.Net/Analysis/TokenAttributes/CharTermAttribute.cs
> +        ISpanAppendable /* LUCENENET specific */
I am good with reverting it due to that justification.

2024-11-19 20:43 UTC, paulirwin commented on src/Lucene.Net.Tests/Analysis/TokenAttributes/TestCharTermAttributeImpl.cs
> +            Assert.AreEqual("01234567890123456789012345678901234567890123456789", t.ToString());
Good idea, broke those tests out as TestSpanAppendableInterface on both this and TestCharBlockArray.

2024-11-19 20:49 UTC, merged