Add operator overrides for public IComparable types, #683
apache/lucenenet pull request #1056
Opened 2024-12-04 05:03 UTC by paulirwin

- [X] You've read the [Contributor Guide](https://github.com/apache/lucenenet/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://www.apache.org/foundation/policies/conduct.html).
- [ ] You've included unit or integration tests for your change, where applicable.
- [ ] You've included inline docs for your change, where applicable.
- [X] There's an open issue for the PR that you are making. If you'd like to propose a change, please [open an issue](https://github.com/apache/lucenenet/issues/new/choose) to discuss the change or find an existing issue.

Add operator overrides for public IComparable types

Fixes #683

## Description

This is a draft PR, because I'm currently unsure about whether to override Equals and GetHashCode (and if so, how exactly to do that, i.e. what to compare) for QualityQuery. @NightOwl888 - please let me know your thoughts.

This is to resolve the Sonar warning about needing to override the comparison operators for any types that implement IComparable. We are only doing this here for the public types.

2024-12-04 17:02 UTC, NightOwl888 commented
> This is a draft PR, because I'm currently unsure about whether to override Equals and GetHashCode (and if so, how exactly to do that, i.e. what to compare) for QualityQuery. @NightOwl888 - please let me know your thoughts.
> 

Well, being that they didn't override the default behavior (which is reference equality), a direct port would be to override each and then cascade the call to the base class.

--------------------

But given the fact that the comparer uses `queryID` and it says "ID of this quality query" for a description, it would probably be best to use that to compare for equality/hash code. It would keep the equality and compare checks exactly in sync.

BTW - I noticed that the `QualityQuery.CompareTo()` implementation has an exception handler that we can remove because we can use `int.TryParse()` and fallback to string comparison if parsing either side returns `false`.

```c#
        public virtual int CompareTo(QualityQuery other)
        {
            try
            {
                // compare as ints when ids ints
                int n = int.Parse(queryID, CultureInfo.InvariantCulture);
                int nOther = int.Parse(other.queryID, CultureInfo.InvariantCulture);
                return n - nOther;
            }
            catch (Exception e) when (e.IsNumberFormatException())
            {
                // fall back to string comparison
                return queryID.CompareToOrdinal(other.queryID);
            }
        }
```

The constructor could also be improved by using guard clauses on `queryID` and `nameValPairs` since there will be NREs if either is passed `null`. If we do so, we don't need to change `CompareTo()` to account for the fact that `queryID` may be `null` (which it currently doesn't handle).

`#nullable enable` would catch this sort of thing.

2024-12-12 14:37 UTC, NightOwl888 requested changes
Thanks for the PR.

We are getting some build warnings in some types where `Equals(object)` and `GetHashCode()` have not been implemented.

Also, since these are all on nullable types, please use `#nullable enable` within the  `#region Operator overrides` sections and `#nullable restore` prior to `#endregion`. We don't necessarily have to do this on the entire file in this PR.

See the inline comments.

2024-12-12 14:37 UTC, NightOwl888 commented on src/Lucene.Net.Suggest/Suggest/Lookup.cs
>                  return CHARSEQUENCE_COMPARER.Compare(Key, o.Key);
Please override `Equals(object)` and `GetHashCode()` to suppress the warnings.

I think the most logical thing to do here is to continue using reference equality by cascading the calls to the base class.

2024-12-12 22:08 UTC, paulirwin commented on src/Lucene.Net.Benchmark/Quality/QualityQuery.cs
> +        protected bool Equals(QualityQuery? other) => queryID == other?.queryID;
That is how Rider generates it, so that subclasses (or any other private callers) don't have to do all the ReferenceEquals/GetType/etc. dance in the `object` version, but I'll remove it for now.

2024-12-13 03:10 UTC, NightOwl888 requested changes

2024-12-13 03:10 UTC, NightOwl888 commented on src/Lucene.Net.Suggest/Suggest/Fst/FSTCompletion.cs
> +                unchecked
Please cascade the call to the base class.

```c#
public override int GetHashCode() => base.GetHashCode();
```

2024-12-13 03:10 UTC, NightOwl888 commented on src/Lucene.Net.Suggest/Suggest/Fst/FSTCompletion.cs
> +            public override bool Equals(object obj) => ReferenceEquals(this, obj);
Please cascade the call to the base class.

```c#
public override bool Equals(object obj) => base.Equals(obj);
```

2024-12-13 03:10 UTC, NightOwl888 commented on src/Lucene.Net.Suggest/Suggest/Lookup.cs
> +            public override bool Equals(object obj) => ReferenceEquals(this, obj);
Please cascade the call to the base class.

```c#
public override bool Equals(object obj) => base.Equals(obj);
```

2024-12-13 03:10 UTC, NightOwl888 commented on src/Lucene.Net.Suggest/Suggest/Lookup.cs
> +            public override int GetHashCode()
Please cascade the call to the base class.

```c#
public override int GetHashCode() => base.GetHashCode();
```

2024-12-13 03:10 UTC, NightOwl888 commented on src/Lucene.Net/Util/Automaton/State.cs
> +        public override bool Equals(object obj) => ReferenceEquals(this, obj);
Please cascade the call to the base class.

```c#
public override bool Equals(object obj) => base.Equals(obj);
```

2024-12-13 15:24 UTC, paulirwin commented on src/Lucene.Net.Suggest/Suggest/Fst/FSTCompletion.cs
> +                unchecked
Rider was giving a code analysis warning of having an override that just calls to the base class. If you prefer it that way, I'll suppress that warning for now. I figured it would be better to be explicit about the expectation of the behavior of Equals.

2024-12-13 15:36 UTC, eladmarg commented
there is a big performance penalty for using this inside try/catch block.
its much better to use this with TryParse and avoid this block for so hot-path function.

2024-12-13 16:08 UTC, NightOwl888 requested changes

2024-12-13 16:08 UTC, NightOwl888 commented on src/Lucene.Net.Highlighter/VectorHighlight/FieldPhraseList.cs
> +            #nullable enable
Actually, it is sensible to have `#region` indented because that is the way Visual Studio formats it.

`#nullable` acts like `#pragma` in that they don't need to be paired and don't need to respect other code elements such as curly brackets. These are both compiler directives. `#region` is something that only an IDE understands and must be paired with `#endregion`.

Hopefully, we will eventually move the `#nullable` statements up to the top of the file or to an MSBuild file. It is helpful to have them left aligned to make them stand apart because eventually they may be removed, but we don't want to remove the `#region` when that happens.

2024-12-13 16:52 UTC, paulirwin commented on src/Lucene.Net.Highlighter/VectorHighlight/FieldPhraseList.cs
> +            #nullable enable
I think this looks rather silly, but updated 😄

2024-12-13 16:54 UTC, paulirwin commented on src/Lucene.Net.Suggest/Suggest/Lookup.cs
> -                unchecked
Created #1065

2024-12-14 12:31 UTC, NightOwl888 approved these changes

2024-12-15 15:57 UTC, merged