Dispose of some disposables, #265, #615
apache/lucenenet pull request #1074
Opened 2024-12-22 16:55 UTC by paulirwin

- [X] You've read the [Contributor Guide](https://github.com/apache/lucenenet/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://www.apache.org/foundation/policies/conduct.html).
- [ ] You've included unit or integration tests for your change, where applicable.
- [X] You've included inline docs for your change, where applicable.
- [X] There's an open issue for the PR that you are making. If you'd like to propose a change, please [open an issue](https://github.com/apache/lucenenet/issues/new/choose) to discuss the change or find an existing issue.

Disposes of some IDisposable objects that are not properly cleaned up.

Fixes #615
Partial #265

## Description

This adds `using` statements to clean up some disposable objects where it's possible to do so, after a review of our codebase with CA2000 code analysis warnings on, where the objects were determined to not "leak" via fields, return values, or the like. This also fixes two FileStream leaks in demo code, #615.

Note that CA2000 is _way_ too noisy to leave on, as there are literally hundreds of "violations" that would make our code a mess with `#pragma` suppressions. The Java upstream code is perhaps a little loose with keeping track of ICloseable lifetimes, but we have to match that in most cases. The cases fixed here were just ones where the object lifetime did not escape the method and it was safe to do so.

2024-12-22 17:14 UTC, NightOwl888 commented on src/Lucene.Net.TestFramework/Search/ShardSearchingTestBase.cs
> +                    using LineFileDocs docs = new LineFileDocs(Random, DefaultCodecSupportsDocValues);
This will force cleanup of the files immediately after running this test, even if they are extracted to a temp directory. We probably don't want to do this because it will slow down the tests a lot, or at least we should figure out how to exclude them from being cleaned up if they are using temp files.

The [UseTempLineDocsFileRule](https://github.com/apache/lucenenet/blob/85c01412946ed1e2632cd2dfae4c672efd38caba/src/Lucene.Net.TestFramework/Support/Util/UseTempLineDocsFileRule.cs) is meant to extract and then clean up the files after the entire test project is finished running.

2024-12-24 18:08 UTC, NightOwl888 requested changes
Thanks for the PR.

I agree that keeping CA2000 on would not be a great idea. That being said, some of these had real underlying issues, but others also inadvertently cause `Dispose()` to be called multiple times on the underlying stream. What is your estimate on how thorough this review is?

`IDisposable` is a leaky abstraction, so when it is implemented in a base class all of the subclasses automatically inherit it even if they don't require it. I think the Lucene team is pretty thorough about declaring most of them properly, but there are some exceptions to this. It would be good to catch those exceptions before the release, if possible.

2024-12-25 03:13 UTC, paulirwin commented on src/Lucene.Net.Analysis.Kuromoji/Dict/BinaryDictionary.cs
> +            using (var @in = new InputStreamDataInput(mapIS)) // LUCENENET: CA2000: Use using statement
While I don't disagree with having leaveOpen versions, it should be noted that there's nothing wrong with calling dispose on the stream more than once. IDisposable guidance[1] is that Dispose should be able to be called more than once without issue, and the .NET BCL types are very good about ensuring this is true. I tested this with FileStream and StreamReader/Writer without issue before submitting this PR. Compared to the performance of i.e. writing to a file, an extra Dispose call is negligible performance-wise as well. That said, I don't see a good reason _not_ to go ahead and do these changes, so I'll knock them out.

1: https://learn.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-dispose
> To help ensure that resources are always cleaned up appropriately, a [Dispose](https://learn.microsoft.com/en-us/dotnet/api/system.idisposable.dispose) method should be idempotent, such that it's callable multiple times without throwing an exception. Furthermore, subsequent invocations of [Dispose](https://learn.microsoft.com/en-us/dotnet/api/system.idisposable.dispose) should do nothing.

2024-12-25 23:13 UTC, paulirwin commented on src/Lucene.Net/Util/Constants.cs
> -            using RegistryKey ndpKey = RegistryKey.OpenBaseKey(RegistryHive.LocalMachine, RegistryView.Registry32).OpenSubKey(subkey);
Filed https://github.com/dotnet/docs/issues/44083

2024-12-25 23:33 UTC, paulirwin commented on src/Lucene.Net.Analysis.Kuromoji/Tools/ConnectionCostsWriter.cs
> +            string filename = System.IO.Path.Combine(baseDir, nameof(ConnectionCosts) + CharacterDefinition.FILENAME_SUFFIX);
Split as #1077

2024-12-26 13:30 UTC, NightOwl888 approved these changes

2024-12-26 15:43 UTC, merged