Review for CA1822: Mark members as static
apache/lucenenet pull request #690
Opened 2022-10-16 17:11 UTC by nikcio

#663 

This should target almost all of the issues currently reported in #663 but I think there will come more of the same issues after this is merged and scanned due to all the new methods now being static. So don't close the issue just yet.

It's mostly just adding `static` and a comment. But some places I've also changed the code to work with the new static classes. I should only have changed the code in some tests.

I've also added `virtual` to classes that I found had the `final` keyword in the Java source code.

2022-10-16 18:56 UTC, NightOwl888 requested changes

2022-10-16 18:56 UTC, NightOwl888 commented on src/Lucene.Net.TestFramework/Support/Util/LuceneRandomSeedInitializer.cs
> +        private static bool TryGetRandomSeedsFromContext(Test test, out long seed, out long? testSeed) // LUCENENET: CA1822: Mark members as static
No need for a comment in a Support folder. At least for stuff that we created as a shim to make Lucene work. But do be aware that there are 2 packages in Benchmark and one in Phonetic that we have made part of the assembly instead of creating separate NuGet packages and repositories to maintain.

2022-10-16 18:56 UTC, NightOwl888 commented on src/Lucene.Net.Tests.Analysis.Phonetic/Language/MatchRatingApproachEncoderTest.cs
> +            Assert.AreEqual("BUBLE", MatchRatingApproachEncoder.RemoveDoubleConsonants("BUBBLE"));
Encoder instances are meant to be interchangeable, so we need to keep these methods available through `this.StringEncoder`, not as a static methods. I am referring to all of the methods under test in this class.

https://github.com/apache/commons-codec/blob/1.9/src/test/java/org/apache/commons/codec/language/MatchRatingApproachEncoderTest.java#L87

2022-10-16 18:56 UTC, NightOwl888 commented on src/Lucene.Net/Index/DocumentsWriterFlushQueue.cs
> +            protected virtual void FinishFlush(IndexWriter indexWriter, FlushedSegment newSegment, FrozenBufferedUpdates bufferedUpdates)
This is marked final in Lucene 4.8.0, so should not be made virtual. Also, it is more sensible as an instance method.

```java
protected final void finishFlush(IndexWriter indexWriter, FlushedSegment newSegment, FrozenBufferedUpdates bufferedUpdates)
            throws IOException {
```

2022-10-16 18:56 UTC, NightOwl888 commented on src/Lucene.Net/Index/FreqProxTermsWriterPerField.cs
> +        public static void Abort()
This method was not marked final in Lucene 4.8.0, therefore it should be made `virtual`.

```java
  public void abort() {}
```

2022-10-16 18:56 UTC, NightOwl888 commented on src/Lucene.Net.TestFramework/Support/Util/LuceneTestFrameworkInitializer.cs
> +        protected static Random Random => LuceneTestCase.Random; // LUCENENET: CA1822: Mark members as static
This is just meant to be a shortcut so we don't have to access the static `LuceneTestCase.Random` method in a subclass of `LuceneTestFrameworkInitializer`. It should be an instance property, and should not be `virtual`.

2022-10-16 18:56 UTC, NightOwl888 commented on src/Lucene.Net/Index/TermVectorsConsumerPerField.cs
> +        public static void Abort() // LUCENENET: CA1822: Mark members as static
This method was not marked final in Lucene 4.8.0, therefore it should be made `virtual`.

```java
  public void abort() {}
```

2022-10-16 19:26 UTC, NightOwl888 commented
> I've also added virtual to methods that I found had the final keyword in the Java source code.

virtual is the opposite of final.

## Java

- `public`/`protected` methods implicitly default to `virtual` (there is no `virtual` keyword in Java, but they are overridable)
- To make `public`/`protected` methods non-overridable, explicitly mark them `final`
- When a subclass overrides a method, it can be explicitly marked `final` to make it non-overridable

## C#

- `public`/`protected` methods (and properties) implicitly default to `sealed`
- To make `public`/`protected` methods overridable, explicitly mark them `virtual`
- When a subclass overrides a method, it can be explicitly marked `sealed` to make it non-overridable

2022-10-16 19:35 UTC, nikcio commented
Oh then I misunderstood your description in #663. I'll look at correcting the mistakes later this week😅

2022-10-17 06:32 UTC, nikcio commented on src/Lucene.Net.Tests.Analysis.Phonetic/Language/MatchRatingApproachEncoderTest.cs
> +            Assert.AreEqual("BUBLE", MatchRatingApproachEncoder.RemoveDoubleConsonants("BUBBLE"));
This has been reverted and methods used here have also been reverted to non-static.

2022-10-17 06:33 UTC, nikcio commented on src/Lucene.Net/Index/FreqProxTermsWriterPerField.cs
> +        public static void Abort()
This is a sealed class and cannot be marked virtual 😄

2022-10-17 06:34 UTC, nikcio commented on src/Lucene.Net/Index/TermVectorsConsumerPerField.cs
> +        public static void Abort() // LUCENENET: CA1822: Mark members as static
This is a sealed class and cannot be marked virtual 😄

2022-10-17 06:35 UTC, nikcio commented
@NightOwl888 Review changes have now been made.

2022-10-17 10:22 UTC, NightOwl888 commented on src/Lucene.Net/Index/FreqProxTermsWriterPerField.cs
> +        public static void Abort()
I took a look and this method is not being called, so it is dead code. I ran the tests to confirm it has no purpose. So, the appropriate thing to do would be to remove it and replace it with a comment.

```
// LUCENENET: Removed Abort() method because it is not in use.
```

2022-10-17 10:22 UTC, NightOwl888 commented on src/Lucene.Net/Index/TermVectorsConsumerPerField.cs
> +        public static void Abort() // LUCENENET: CA1822: Mark members as static
I took a look and this method is not being called, so it is dead code. I ran the tests to confirm it has no purpose. So, the appropriate thing to do would be to remove it and replace it with a comment.

```
// LUCENENET: Removed Abort() method because it is not in use.
```

2022-10-17 10:37 UTC, NightOwl888 requested changes
So, looks like most of what remains are `private` which are fine to make static. There are no protected members in the changeset. And I have reviewed the `public` members. After we remove the two `Abort()` methods and replace them with a comment (see the inline conversations), this is good to merge.

2022-10-17 10:45 UTC, nikcio commented
The `Abort` methods have now been replaced with a comment.

2022-10-17 10:57 UTC, NightOwl888 commented
Actually, have you kept track of the methods we decided not to mark static that are triggering this warning? If so, we should suppress those via attribute.

```c#
[SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "By design")]
```

If you haven't kept track:

1. We can merge this to master and then scan, and then submit a new PR with these attributes.
2. Scan this branch to find the CA1822 warnings and fix them before the merge.
3. Use Visual Studio to scan the entire solution for CA1822, and submit another commit to this PR with these attributes.
4. Use the conversations above to try to work it out, but I think we may miss some that way. Most likely we would need another PR to add attributes where they are missing.

Any option is fine.

2022-10-17 11:12 UTC, nikcio commented
@NightOwl888 There's two that I couldn't change due to them causing errors these are:

https://sonarcloud.io/project/issues?issues=AYPAuN5xhbfJOGLOoaDV&open=AYPAuN5xhbfJOGLOoaDV&id=nikcio_lucenenet

https://sonarcloud.io/project/issues?issues=AYPAuOHjhbfJOGLOoaMN&open=AYPAuOHjhbfJOGLOoaMN&id=nikcio_lucenenet

I've marked them in SonarCloud.

But regarding the rest of the changes in the review phase here I haven't had the time to mark them in SonarCloud yet. Therefore, I think the best approach would be to merge these changes as is and create a new PR with the attributes on the warnings we can rule out like the two links above and the ones that have been caught in the review process here.

I think that doing a branch sweep for the warning is a little to early just yet because the new static methods might have opened up for more methods being available to be made static. Therefore, we cannot be sure that the next scan is only the cases we have found to be unable to be marked static.

2022-10-17 11:15 UTC, nikcio commented
We should be able to find all the cases where we have decided that we cannot mark methods static in this commit: https://github.com/apache/lucenenet/pull/690/commits/bbf4289e7a689fddec14a7575702f2335e6d94a7

2022-10-17 11:36 UTC, NightOwl888 commented
> We should be able to find all the cases where we have decided that we cannot mark methods static in this commit: [bbf4289](https://github.com/apache/lucenenet/commit/bbf4289e7a689fddec14a7575702f2335e6d94a7)

Yea, that looks like it could work for what we have in this PR. You can go ahead and move the attribute up to the class level for the one test class instead of putting it on every test method (although, not sure why we are getting a test class, since the CA1822 warning suppression is explicitly configured in all of the test projects).

But, you are right about the cascade effect of warnings that happen due to fixing these. We had already fixed these once, and are finding them again. So it may take a few iterations to catch them all.

2022-10-17 16:58 UTC, NightOwl888 approved these changes

2022-10-17 17:02 UTC, merged