Fix slow test: use different sleep method if resolution is low
apache/lucenenet pull request #838
Opened 2023-04-21 18:43 UTC by laimis

This fixes an issue with a slow test in TestTaxonomyCombined. The original issue description is here:

The issue has been brought up in https://github.com/apache/lucenenet/issues/836, under `TestTaxonomyCombined.TestTaxonomyRefreshRaces()` section

After debugging the issue, I discovered that the cause of the slow down are System.Thread.Sleep(1) calls being made thousands of times with intent of sleep taking 1ms. On windows however, that could take much more than 1ms, 15ms normally, confirmed locally and found a discussion about it here:

https://stackoverflow.com/questions/19066900/thread-sleep1-takes-longer-than-1ms

I setup Java version locally to compare the running times and after the fix, Java version and .NET version is running in basically identical amount of time. Locally I get it to run in 3-4s range, the same with Java version. Before the fix, it took 30-40s depending on what random generated loop variable values were.

2023-04-21 18:44 UTC, laimis commented on src/Lucene.Net.TestFramework/Index/RandomCodec.cs
Put this back as they were showing up in console and interfering with debugging.

2023-04-21 18:57 UTC, laimis commented
The failing tests do not appear to be there due to my changes.

return new J2N.Randomizer(random.NextInt64());

NextInt643= is not available on Random before .net 6. Not sure what the fix here is for that, let me know if you have any suggestions, @NightOwl888 . Thanks!

2023-04-21 23:08 UTC, laimis commented
I think I see what I can do here next, remove .net5 and .net46 targets for the facet project should make the issue go away. Me removing Slow attribute enabled a new code path. Should be able to adjust later today.

2023-04-22 16:34 UTC, NightOwl888 commented
> Not sure how to proceed here. It feels like we either stop using NextInt64 or drop .net5?

[NextInt64()](https://github.com/NightOwl888/RandomizedTesting/blob/main/src/RandomizedTesting.Generators/Support/RandomExtensions.cs#L119) is an extension method in RandomizedTesting.Generators. However, I noticed that it doesn't cascade the call to the correct random implementation when the `Random` instance is a `J2N.Randomizer`, which I have submitted a fix for in https://github.com/NightOwl888/RandomizedTesting/pull/1. That won't affect what you are doing, though and we can upgrade RandomizedTesting.Generators later.

We most definitely do not want to drop tests for `net5.0` and `net461` as that would leave a gap in our test coverage. Namely, we wouldn't have any tests for the `netstandard2.1` or `netstandard2.0` assemblies.

2023-04-22 18:41 UTC, NightOwl888 requested changes

2023-04-22 18:41 UTC, NightOwl888 commented on src/Lucene.Net.Tests.Facet/Taxonomy/TestTaxonomyCombined.cs
> -        [Slow]
I have been using 4 seconds on my machine as a minimum for what is considered a slow test. This is actually right on the edge after the above updates, so this could go either way.

2023-04-22 18:41 UTC, NightOwl888 commented on src/Lucene.Net.Tests.Facet/SlowRAMDirectory.cs
> +                if (sTime > MINIMUM_SUPPORTED_THREAD_SLEEP_TIME)
Good work finding this cause!

However, the resolution of `Stopwatch` varies depending on the OS, so we cannot use a constant for this. I used ChatGPT to come up with a solution that

1. Doesn't allocate a `Stopwatch` instance
2. Doesn't block the CPU
3. Correctly calculates the number of ticks to wait for the current platform
4. Can be used as a drop-in replacement for `Thread.Sleep()` in this instance

```c#
internal virtual void DoSleep(Random random, int length)
{
    int sTime = length < 10 ? sleepMillis : (int)(sleepMillis * Math.Log(length));
    if (random != null)
    {
        sTime = random.Next(sTime);
    }

    try
    {
        Sleep(sTime);
    }
    catch (Exception ie) when (ie.IsInterruptedException())
    {
        throw new Util.ThreadInterruptedException(ie);
    }
}

internal static void Sleep(int milliseconds)
{
    long ticks = (long)((Stopwatch.Frequency / (double)1000) * milliseconds); // ticks per millisecond * milliseconds = total delay ticks
    long initialTick = Stopwatch.GetTimestamp();
    long targetTick = initialTick + ticks;
    while (Stopwatch.GetTimestamp() < targetTick)
    {
        Thread.SpinWait(1);
    }
}
```

On my system this branch takes at least 6 seconds to run `TestTaxonomyReaderRefreshRaces()`, but with these changes it drops to 4 or 5 seconds.

I confirmed that the CPU is not pegged at 100% when `Sleep()` runs, but I haven't done any testing other than on Windows.

2023-04-23 02:14 UTC, laimis commented
Figured out what's up with the NextInt64 call, I removed the using for extension method as my IDE showed it as not being used, but as we can see, that gets used under different .net framework versions. I will have to keep that in mind.

2023-04-23 02:14 UTC, laimis commented
@NightOwl888 ready for your review again.

2023-04-23 02:20 UTC, NightOwl888 commented
> Figured out what's up with the NextInt64 call, I removed the using for extension method as my IDE showed it as not being used, but as we can see, that gets used under different .net framework versions. I will have to keep that in mind.
Actually, since we consistently use J2N.Randomizer, it will call the overridden NextInt64() since it is a subclass of System.Random. The concrete method takes precedence over the extension method. But as previously mentioned, the extension method currently has a different implementation than the concrete method, so it will vary depending on whether dotnet supplies the method or not.

2023-04-23 03:47 UTC, NightOwl888 requested changes
Just 1 small change to make.

As we discussed in Slack, let's also open an [issue in J2N](https://github.com/NightOwl888/J2N/issues) to work on a more precise `ThreadJob.Sleep()` implementation for general use in Lucene.NET. This implementation (or one very similar) might work there, but we will need to use the `TestThreadInterruptDeadlock()` tests to confirm that it will throw a `ThreadInterruptedException` when `Thread.Interrupt()` is called. If it doesn't, we will need to find a way to throw one.

2023-04-23 03:47 UTC, NightOwl888 commented on src/Lucene.Net.Tests.Facet/Taxonomy/TestTaxonomyCombined.cs
> -        [Slow]
Let's keep the `[Slow]` attribute since this is almost always over 4 seconds on my machine even after the improvement.

This can be used to get a faster run by setting the system property `tests: slow` to `false` to exclude the tests that are marked with this attribute. We currently only use that for the CLI installer test in GitHub actions, but it is also possible to set in Azure DevOps by passing in `RunSlowTests` as `false`.

2023-04-23 04:03 UTC, NightOwl888 approved these changes

2023-04-23 04:06 UTC, merged