Upgrade tests and CLI to .NET 8, fix benchmark formatting issue
apache/lucenenet pull request #930
Opened 2024-03-13 03:35 UTC by paulirwin

- [X] You've read the [Contributor Guide](https://github.com/apache/lucenenet/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://www.apache.org/foundation/policies/conduct.html).
- [X] You've included unit or integration tests for your change, where applicable.
- [X] You've included inline docs for your change, where applicable.
- [X] There's an open issue for the PR that you are making. If you'd like to propose a change, please [open an issue](https://github.com/apache/lucenenet/issues/new/choose) to discuss the change or find an existing issue.

.NET 8 upgrade for test and CLI projects.

Partial #928

## Description

- Replaces net7.0 with net8.0 for unit tests
- Changes CLI to target net8.0 instead of net7.0
- Removes `FEATURE_SERIALIZABLE` and `FEATURE_SERIALIZABLE_EXCEPTIONS` for net7.0+ where BinaryFormatter is deprecated (and throws an exception in .NET 8)
- Fixes a formatting bug in the CLI sample benchmark

NOTE: net6.0 is still the latest target for the libraries at this time. This just ensures we're testing with .NET 8, as well as providing a .NET 8 CLI.

2024-03-13 09:43 UTC, NightOwl888 requested changes
Thanks for the PR.

This currently doesn't run on Azure DevOps because there were a couple omissions.

- https://github.com/apache/lucenenet/blob/b1476aee4fe21131899c1f43b2e06e25971b3ebe/.build/runbuild.ps1#L30
- https://github.com/apache/lucenenet/blob/b1476aee4fe21131899c1f43b2e06e25971b3ebe/azure-pipelines.yml#L58

There is also a bug here:
https://github.com/apache/lucenenet/blob/b1476aee4fe21131899c1f43b2e06e25971b3ebe/.build/azure-templates/run-tests-on-os.yml#L111

2024-03-13 15:15 UTC, paulirwin commented on src/dotnet/tools/lucene-cli/.gitignore
> +﻿work/
The justification/benefit here is if the lucene-cli folder ends up getting moved/renamed in the future the gitignore still works, which is one reason why I tend to prefer this approach instead of listing the full `src/dotnet/tools/lucene-cli/work/` in the root .gitignore. Let me know if that jibes with you, if not I can make that change.

2024-03-13 18:17 UTC, NightOwl888 commented on src/dotnet/tools/lucene-cli/lucene-cli.csproj
> +    <RollForward Condition=" $(TargetFramework.StartsWith('net8.')) ">Major</RollForward>
IMO, allowing the user to roll forward is the best solution. Here is the situation we are planning for:

Eventually, we will be caught up with the Lucene release schedule, hopefully to the point where we release every minor version. Some of the lucene-cli tools that ship with every version of Lucene.NET are **version sensitive** down to the minor version. Let's say in the future we release Lucene 10.0 through 10.10 on .NET 8, .NET 9, and .NET 10 (lucene-cli is part of that release).

Now a user is using Lucene 10.3 and has his index built on that codec. The app works fine and is stable on that release, so they stick with it a few years and all of the .NET SDKs that lucene-cli shipped with are now obsolete. He doesn't notice this because `net10.0` DLLs will run fine on `net13.0` which he eventually targets. The user's index gets corrupted and he needs to run the fix utility immediately. He installs lucene-cli from the command line to do the fix and then when he runs it there is an error that no supported runtime is installed because he has .NET 12 and .NET 13.

There are only 4 ways out of this scenario:

1. We plan ahead for this situation and document how to get lucene-cli 10.3 up and running on .NET 13 after .NET 10 is out of support.
2. We plan to do a patch release of every minor Lucene version every time a .NET version is released so we can stay ahead of the planned obsolescence. In this scenario, we would need to patch Lucene.NET 10.0 through 10.10 for .NET 11, .NET 12, and .NET 13 (that is, 3 different patches as each new SDK is released for 11 different releases).
3. The user has to install an out of support .NET runtime in order to fix his index. And maybe he can't because his company has a policy against it.
4. The user has to download the source code and recompile on `net13.0`, then work out how to install the the tool from the lucene-cli NuGet package in a local directory onto his machine before he can run it.

In this scenario, upgrading Lucene.NET to the latest version is not a viable option because the tools on the latest version may not have binary compatibility with his index.

The documentation you linked to assumes a Framework Dependent DLL distribution, not a [dotnet tool](https://learn.microsoft.com/en-us/dotnet/core/tools/global-tools). Which kind of underlines my point. You cannot just do `dotnet run` with a .NET tool, you have to install it from NuGet and it ships with support for specific runtimes. So a user who ends up there won't have a solution to the problem, and won't appreciate that we don't have a document to get the tool to fix his index running.

I *wish* we didn't have to have a `lucene-cli`. In Java, you can simply use the JAR you have in your app directory and run the tools inside of it on the command line (in addition to depending on it like a class library). That approach means that the tool is always available to run regardless of which version of Java is installed. Unfortunately, since we need an executable to be able to run on the command line in .NET, we needed another solution that we could ship with Lucene.NET so the user wouldn't have to deal with compiling from source. lucene-cli is a wrapper executable that simply cascades calls to the `Main()` methods inside of the (non-executable) DLLs and also cleans up the commands to make them more consistent. So, yes there is a guarantee they will work well because they are the same DLLs that the user is already using that work well.

Of course, I am open to suggestions about an alternative way to ship the Lucene tools and to keep them ahead of the .NET planned obsolescence, but IMO it makes more sense to provide a compiled app that is ready to go than source code that a user has to build. And then Microsoft made that hard for those of us shipping version-sensitive code.

2024-03-13 18:58 UTC, NightOwl888 commented on src/dotnet/tools/lucene-cli/.gitignore
> +﻿work/
Willing to give this a try.

But, I guess the reason you needed this is because you ran the tool locally in the source code directory...? I didn't think of running it that way but I guess a user could if they wanted to.

Typically, this would be installed from [NuGet](https://www.nuget.org/packages/lucene-cli/) on the command line: https://lucenenet.apache.org/docs/4.8.0-beta00016/cli/index.html#installation so the work directory doesn't typically end up in the repository.

2024-03-13 19:18 UTC, paulirwin commented on src/dotnet/tools/lucene-cli/.gitignore
> +﻿work/
Yes indeed, I ran this via `dotnet run` in that folder. I'd imagine that would be a fairly common scenario for someone exploring the source code locally or debugging it. I'll leave this in place for now, thanks!

2024-03-13 19:44 UTC, paulirwin commented on src/dotnet/tools/lucene-cli/lucene-cli.csproj
> +    <RollForward Condition=" $(TargetFramework.StartsWith('net8.')) ">Major</RollForward>
I agree with leaving this as the Major roll-forward strategy, and I appreciate the amount of thought you've put into this. But if we can't test effectively with .NET 9 because we don't know what will break in the future, then by definition we just have to accept the risk that a future .NET version will break it for now and leave this as-is. It's already in the repo, so it's not like this PR changes anything from the current state in this regard.

2024-03-13 21:06 UTC, paulirwin commented on src/dotnet/tools/lucene-cli/lucene-cli.csproj
> +    <RollForward Condition=" $(TargetFramework.StartsWith('net8.')) ">Major</RollForward>
Alright, good and maybe weird results. I set up a fresh Ubuntu VM and only installed the .NET 8 SDK onto it. I installed the global tool with `dotnet tool install --global lucene-cli --version 4.8.0-beta00016`. If you just run `lucene`, you get the error that you must install .NET 6 (which is the weird part, maybe it prefers LTS to STS .NET 7?). 

However, the options at the link I sent before _do_ work for global tools. You can force it to run on .NET 8 with `lucene --roll-forward LatestMajor`. For example, `lucene --roll-forward LatestMajor benchmark sample` works. Note that Major does not work, only `LatestMajor`. You also can override it without the CLI flag by setting the `DOTNET_ROLL_FORWARD` environment variable to `LatestMajor`.

Given that it does work to override it manually with the tool installation, I'd say we can either remove this, or try setting the roll forward strategy to LatestMajor (although that might be a little risky, and not what some users want). My vote would be for the former and remove the explicit strategy, defaulting to Minor, letting users override it if they wish.

2024-03-13 21:09 UTC, paulirwin commented on src/dotnet/tools/lucene-cli/lucene-cli.csproj
> +    <RollForward Condition=" $(TargetFramework.StartsWith('net8.')) ">Major</RollForward>
Disregard the "weird" part, beta 16 targets net6.0.

2024-03-13 21:42 UTC, paulirwin commented on src/dotnet/tools/lucene-cli/lucene-cli.csproj
> +    <RollForward Condition=" $(TargetFramework.StartsWith('net8.')) ">Major</RollForward>
I see now that the roll forward Major setting was added to lucene-cli after beta 16, but regardless, setting it to Major manually does not work for that version while LatestMajor does, so users are not stuck if they somehow can't install the older .NET.

2024-03-14 03:32 UTC, NightOwl888 commented on src/dotnet/tools/lucene-cli/lucene-cli.csproj
> +    <RollForward Condition=" $(TargetFramework.StartsWith('net8.')) ">Major</RollForward>
If you can get `LatestMajor` to work implicitly, that would be best. But when we tried before, there was no option that worked implicitly. And Microsoft doesn't seem to want to change that. Per https://github.com/dotnet/sdk/issues/30336#issuecomment-1620664270:

> Our compat bar is based on the idea that no scenarios auto roll-forward. I think we should keep to that.

Whether we can get it to work implicitly or not, I think this should be documented somewhere for users so they understand that we ship with specific .NET Core targets that may be out of support by the time the user digs up the tools to use them and (if possible) we will roll forward to the latest .NET runtime that is installed.

If there were a way to do it implicitly, ideally we would only target the *lowest supported* target framework, which would decrease our deployment size considerably. However, I did some experimentation and couldn't find a way to make that work without an explicit command from the user.

Having that `DOTNET_ROLL_FORWARD` environment variable documented on our [installation page](https://github.com/apache/lucenenet/blob/63e1053b6cad1b874563400fbe83a708d5c0fa17/src/dotnet/tools/lucene-cli/docs/index.md) would definitely be a fast and low risk way out of the user scenario I described. Ideally, there would be other options documented as well (such as adding `--roll-forward` to each command).

> it does work to override it manually with the tool installation

Did you try explicitly setting the [`--framework`](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-tool-install) on installation to one higher than our NuGet package ships with?

> I installed the global tool with `dotnet tool install --global lucene-cli --version 4.8.0-beta00016`

Yeah, you will need to override the nuget.org source by using `--add-source <SOURCE>` pointing to your local directory where the master branch-built lucene-cli exists. Then you can experiment with changes to the code instead of relying on the decisions that were made in 4.8.0-beta00016. There is an [installation test](https://github.com/apache/lucenenet/blob/63e1053b6cad1b874563400fbe83a708d5c0fa17/src/dotnet/tools/Lucene.Net.Tests.Cli/InstallationTest.cs) that demonstrates this approach.

2024-03-24 22:04 UTC, paulirwin commented on src/dotnet/tools/lucene-cli/lucene-cli.csproj
> +    <RollForward Condition=" $(TargetFramework.StartsWith('net8.')) ">Major</RollForward>
Alright the master-built 4.8.0-ci package for lucene-cli installs and runs fine without specifying the environment variable or command-line flag to roll forward, with only .NET 8 installed. `--framework` doesn't seem to affect it AFAICT. Given that Major roll-forward works here, I think we can consider this item complete. Anything else to do here on this PR?

2024-03-28 15:08 UTC, NightOwl888 requested changes
The build succeeds on Azure DevOps now, but there are some issues with the x86 tests not running. I think it is due to a duplicate installation of the .NET SDK. But before that is fixed, we should fix the crash detection to account for yet another way a build can fail so we can see the failure if something like this happens in the future. See my inline comments for details.

2024-03-28 23:23 UTC, paulirwin commented on src/dotnet/tools/lucene-cli/lucene-cli.csproj
> +    <RollForward Condition=" $(TargetFramework.StartsWith('net8.')) ">Major</RollForward>
Documentation added!

2024-03-28 23:29 UTC, paulirwin commented on TestTargetFramework.props
> +  <PropertyGroup Label="net5.0 Warnings to be Disabled in Test Projects" Condition=" '$(TargetFramework)' == 'net5.0' ">
Done

2024-04-02 05:44 UTC, NightOwl888 commented
I setup a new repository with our Azure DevOps templates and discovered that there are some breaking changes.

### Breaking Change 1

There is a breaking change introduced by Microsoft in the .NET 8 SDK, which appends the Git commit hash to the `AssemblyInformationalVersion`: https://github.com/dotnet/sdk/issues/34568. We already add a shortened Git commit hash, so this will add it twice. The fix should definitely be in this PR, since this is where we introduce building with the .NET 8 SDK.

More info about it is here: https://learn.microsoft.com/en-us/dotnet/core/compatibility/sdk/8.0/source-link. I have tested the solution and it seems to meet our needs. However, the first build after I changed it caused the NuGet packages to be built without any DLLs in them, but the second build succeeded. Not sure whether that was a fluke or a problem.

We can put the fix in the default `Directory.Build.targets` file of the solution (in each repository):

```xml
  <PropertyGroup Label="Versioning">
    <GenerateAssemblyVersionInfo>false</GenerateAssemblyVersionInfo>
  </PropertyGroup>
```

### Breaking Change 2

The default for a new pipeline in Azure DevOps is to create a shallow clone. Previously, it would create a deep clone by default.

This doesn't break anything on Lucene.Net, but all of the other repositories that we own use NerdBank.GitVersioning, and this is a problem for generating the correct version number. There is an issue about it here: https://github.com/dotnet/Nerdbank.GitVersioning/issues/837 and the fix is here: https://github.com/dotnet/Nerdbank.GitVersioning/blob/main/doc/cloudbuild.md#azure-pipelines

We would need to apply that on the "Build" job of all of our repositories. On Lucene.NET, it is already done this way for performance reasons.

### Breaking Change 3

We do a solution-wide publish for the tests on Azure DevOps. This puts all of the DLL files into a single directory as they would be in the real world. So, doing it this way can detect issues with version conflicts between dependencies (in particular, transitive dependencies of libraries that we depend upon). The failure will happen in our test environment rather than waiting for a user to eventually depend on 2 of our packages with conflicting dependency versions.

Unfortunately, Microsoft realized that solution-wide publish to a shared directory will cause "inconsistent builds" and made it fail if you provide the `--output` parameter when publishing on a solution. Here is where I found a solution that works: https://stackoverflow.com/a/75556105 on .NET Framework 4.5 and lower.

However, it is a bit more nuanced than that. [`net451` fixed the automation of assembly binding redirects'](https://learn.microsoft.com/en-us/dotnet/framework/configure-apps/how-to-enable-and-disable-automatic-binding-redirection#disable-automatic-binding-redirects-in-desktop-apps). 

In `build-pack-and-publish-libraries.yml`, we need to change:

```powershell
dotnet publish --output "$outputPath" --framework "$framework" --configuration "$configuration" --no-build --no-restore --verbosity normal /p:TestAllTargetFrameworks=true
```
For solutions still supporting older versions of .NET Framework, we will need to continue publishing to a single directory to find conflicts.

We should publish to separate directories for newer versions of .NET, so there will need to be some branching logic in those solutions. Since we use the same templates, we should just bake this logic in even if the current repo doesn't need it.

I think we may be able to use the new [simplified output path](https://devblogs.microsoft.com/dotnet/announcing-dotnet-8-preview-3/#simplified-output-path) feature of .NET 8 mentioned [here](https://github.com/dotnet/msbuild/issues/3497#issuecomment-1560451928) for .NET Framework 4.5.1 and higher.

For .NET Framework 4.5 and lower, use:

```powershell
dotnet publish --framework "$framework" --configuration "$configuration" --no-build --no-restore --verbosity normal /p:"PublishDir=$outputPath" /p:TestAllTargetFrameworks=true
```

I haven't gone into all of the nuance of this feature yet, though. We may consider folding our `_artifacts` directory into the new `.artifacts` directory of this feature. And we generally don't want it enabled except in our CI and command-line build scripts. Our tests search all subdirectories for the test DLL name pattern below directories with the name of the target framework:

```powershell
$testBinaries = Get-ChildItem -Path "$testBinaryRootDirectory" -File -Recurse | Where-Object {$_.FullName -match "$framework"} | Where-Object {$_.FullName -match "$fileRegexPattern"} | Select -ExpandProperty FullName
```

So, we aren't tightly coupled to any particular directory structure. It just needs to be tested to confirm it can find test files with this new directory structure. It won't if the target framework is missing from the directory path, but based on their simple examples it isn't clear whether it will be there or not.

Publish takes much longer going one project at a time, so we should continue publishing at the solution level, though.

### Our Other Repositories

This is a list of all of the repositories that use the same Azure DevOps (and command line build) templates that will need to be patched to account for this.

- [J2N](https://github.com/NightOwl888/J2N)
- [ICU4N](https://github.com/NightOwl888/ICU4N)
- [RandomizedTesting](https://github.com/NightOwl888/RandomizedTesting)
- [Spatial4n](https://github.com/Spatial4n/Spatial4n)
- [Morfologik.Stemming](https://github.com/NightOwl888/Morfologik.Stemming)
- [NetFx.Polyfills](https://github.com/NightOwl888/NetFx.Polyfills) (fixes already applied)

While we could just fix the issue in this PR and add 2 issues to each of the other repositories, I think it might be simpler just to submit a PR to each repository with the patches and a link back to this PR.

2024-04-27 16:06 UTC, NightOwl888 commented on .build/runbuild.ps1
> +    [string]$minimumSdkVersion = "8.0.101"
Actually, I am working on this now. Figured we would need to merge it before dealing with #935.

I ran into this issue: https://github.com/dotnet/runtime/issues/88283. Still trying to come up with a solution. For whatever reason, just installing is not enough to get it to find the x86 host anymore.

2024-04-30 16:19 UTC, NightOwl888 approved these changes
The fix for installing the right SDK based on target framework and platform turned out to be quite an ugly piece of code with lots of repeating and special cases. But it works. It took a lot of work because .NET 8 broke quite a few things, like support for .NET Framework 4.6.1 on NUnit.

I think it could be improved by creating a separate `install-dotnet-sdk-for-target-framework.yml` template and putting logic in it to decide which SDKs to install based on target framework and architecture and to make it xplat. But we can probably wait until testing on ARM64 is possible in Azure DevOps before making the changes.

I don't imagine I changed anything that could cause a local build to fail, but as long as this configuration still works on ARM64, it is good to merge pending your review of my changes.

2024-04-30 17:55 UTC, merged