BUG: Fix for DocumentsWriter concurrency (fixes #935, closes #886)
apache/lucenenet pull request #940
Opened 2024-05-23 12:36 UTC by NightOwl888

- [x] You've read the [Contributor Guide](https://github.com/apache/lucenenet/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://www.apache.org/foundation/policies/conduct.html).
- [x] You've included unit or integration tests for your change, where applicable.
- [x] You've included inline docs for your change, where applicable.
- [x] There's an open issue for the PR that you are making. If you'd like to propose a change, please [open an issue](https://github.com/apache/lucenenet/issues/new/choose) to discuss the change or find an existing issue.

Summary of the changes (Less than 80 chars)

Lucene.Net.Support.Threading.ReentrantLock: Fixed the implementation so it prioritizes new threads obtaining the lock over waiting threads.

Fixes #935. Closes #886.

## Description

This has been a known issue for some time, however as we got the `DocumentsWriter` working reliably on a single thread most users have not worried about it until it was reported in #935.

There were 2 issues that were causing test failures explained in https://github.com/apache/lucenenet/issues/935#issuecomment-2118228819. The second issue turned out to be much more involved to work out how to address even though the most recent solution is actually very simple and lightweight. Instead of calling `UninterruptableMonitor.Enter()` in the `Lock()` method, we call `UninterruptableMonitor.TryEnter()` in a loop that executes `Thread.Yield()`. This allows other threads to acquire the lock even though there are waiting threads.

Granted, while this approach seems to reliably pass the tests, it may be a bit naïve of an implementation. While it doesn't peg my CPU and seems to run well on Azure DevOps, I am not sure whether this is the appropriate solution for production scenarios. Suggestions are welcome as to how to improve this. Do note there were 2 prior attempts:

- https://github.com/apache/lucenenet/commit/6f2e1290ac067299c6e9b216649a852ade0a07f8 - Uses a timeout to ensure the lock is acquired, but it still has to wait until the queue schedules it until it runs.
- https://github.com/apache/lucenenet/commit/89b01e625116afd5ccba9457271a36524dc75ca1 - Uses `ManualResetEventSlim` and a `Queue<T>` to manage the waiting threads. This is a more complete implementation and even passed many of the Apache Harmony tests, but it comes at a pretty steep performance cost. Maybe there is a way to improve this, though.

2024-05-23 13:13 UTC, paulirwin commented on src/Lucene.Net.Tests/Support/Threading/ReentrantLockTest.cs
> +            catch (SynchronizationLockException success) { }
It might be cleaner to leave off the pragmas and remove the named catch variable. If you want to indicate that it's success a comment could work, like `catch (SynchronizationLockException /* success */) { }`

2024-05-24 03:15 UTC, NightOwl888 commented on src/Lucene.Net.Tests/Support/Threading/ReentrantLockTest.cs
> +            catch (SynchronizationLockException success) { }
Yep. And SonarCloud also warns against having an empty set of brackets, so I just moved it as a comment there instead.

2024-05-28 16:47 UTC, pc-LMS commented
@jeme @rclabo Hello, I am reaching out to see if you have some time to review the request.  I am hoping to begin using this fix if all goes well :)

2024-05-28 17:53 UTC, rclabo commented
I'll try to free up some time so I can look through this towards the end of the week.  I'm sure I'd learn a lot in the process, so looking forward to it.

2024-06-07 21:17 UTC, rclabo commented
This week, I made good headway toward setting up an environment where I can benchmark the current master vs this PR to see if the proposed improvements do, in fact, speed up indexing through support for DocumentsWriter concurrency.  

For benchmarking I'm using an approach similar to the code provided in [#935](https://github.com/apache/lucenenet/issues/935) to see the level of impact this PR has on the performance issue reported there.  

I will work on this more this next week and provide the results of the benchmarks once I have them.  Then I will review the code in light of those benchmarks.

That's my update for this week.

2024-06-14 21:37 UTC, rclabo commented on src/Lucene.Net.Tests/Support/Threading/JSR166TestCase.cs
Many method names in this file are camelCase. They should be changed to PascalCase as is the norm in the .NET world.

2024-06-14 22:00 UTC, rclabo commented
I have reviewed each of the individual commits for this PR, but since many commits overlap and change the same areas of code I still want to review the aggregate effect on each changed file by comparing it to the Java Lucene 4.8.1 file.  I plan to do that on Monday.

I have also run performance tests on this PR vs the Master prior to the PR and the performance appears to be approximately the same.

2024-06-17 18:13 UTC, rclabo requested changes

2024-06-17 18:13 UTC, rclabo commented on src/Lucene.Net/Index/DocumentsWriterFlushControl.cs
Line 505 contains "flushQueue.Count > 0 &&", which is not found in the corresponding Java Lucene 4.8.1 code. This, however, is a pre-existing deviation rather than a change submitted in this PR. Still, it may be worth investigating why this change was introduced and whether it is still needed.

2024-06-17 18:13 UTC, rclabo commented on src/Lucene.Net/Support/Threading/ReentrantLock.cs
These changes to ReentrantLock overall seem like an elegant solution to get close to parity to how the reentrantLock class works in Java (as far as I understand it based on a bunch of googling). So, in general, this feels like a great step forward. It is, however, imperative that the code be original and not incorporate any OpenJDK code or code from any non-Apache source. Please ensure that is the case.

2024-06-17 18:13 UTC, rclabo commented on src/Lucene.Net/Support/Threading/UninterruptableMonitor.cs
These method should ideally all contain doc comments to explain what they do.

2024-06-18 15:57 UTC, rclabo commented
@pc-LMS
>We also ran a test and did not see any performance improvements - CPU remained at the same level and was not elevated in anyway. 

Today I made a private branch off of of this PR and I hacked in some concurrent logging to memory deep inside the indexing code at the dwpt level.  Specifically I logged to memory each time a thread entered the `documentWriterPerThread.UpdateDocument(...)` method and each time a thread left that method.  Through this code I was able to unequivocally verify that with this PR multiple threads are able to call `documentWriterPerThread.UpdateDocument(...)`  in parallel.  

In my observations during performance testing, I could never get my processor above 45% utilization, and then only for brief spikes, but that kinda makes sense to me given the fact that indexing is pretty clearly an IO bound operation not a CPU bound operation.

Just for fun I created a parallel threading test where I had up to 20 threads reading text files in one format and writing them in another format via an input and output stream per thread.  My local processor has 20 cores.  This 2nd setup doesn't use Lucene.NET in any way but I wanted to see if outside of Lucene.NET I could get high utilization of my CPU  when using lots of threads doing heavy IO work.  And the answer, as I suspected, is no.  My processor never got even above 35% utilization and that just for brief spikes.

2024-08-12 09:05 UTC, NightOwl888 commented on src/Lucene.Net/Support/Threading/UninterruptableMonitor.cs
I added some docs and eliminated the recursive methods that could overflow the stack (in theory).

2024-08-13 15:58 UTC, rclabo commented on src/Lucene.Net.Tests/Support/Threading/ReentrantLockTest.cs
Thanks for the clarification an citing the source.  Great.

2024-08-13 16:01 UTC, rclabo commented on src/Lucene.Net/Support/Threading/ReentrantLock.cs
Sweet.

2024-08-13 16:05 UTC, rclabo commented on src/Lucene.Net.Tests/Support/Threading/JSR166TestCase.cs
> Typically, we haven't been strictly converting method names in test classes except for test method names

If that's the case then no worries.  I was just calling out the case difference since I was unaware of that history.  The casing is fine as submitted then.

2024-08-13 16:07 UTC, rclabo approved these changes
I appreciate your work on this @NightOwl888.  This improved locking implementation tracks MUCH more closely with the original Java implementation.  Super cool to see.

2024-08-13 16:31 UTC, merged